FONT_FAMILY = "Roboto"
BOLD = "bold"
ROMAN = "roman"
STRIKETHROUGH = "overstrike"
ITALIC = "italic"

PXS = 5
PS = 10
PM = 20
PL = 30
PXL = 40

H1 = (FONT_FAMILY, 39, BOLD)
H2 = (FONT_FAMILY, 32, BOLD)
H3 = (FONT_FAMILY, 28, BOLD)
H4 = (FONT_FAMILY, 24, BOLD)
H5 = (FONT_FAMILY, 20, BOLD)
H6 = (FONT_FAMILY, 16, BOLD)

DISPLAY1 = (FONT_FAMILY, 76, ROMAN)
DISPLAY2 = (FONT_FAMILY, 70, ROMAN)
DISPLAY3 = (FONT_FAMILY, 62, ROMAN)
DISPLAY4 = (FONT_FAMILY, 54, ROMAN)
DISPLAY5 = (FONT_FAMILY, 47, ROMAN)
DISPLAY6 = (FONT_FAMILY, 39, ROMAN)

LEAD = (FONT_FAMILY, 20)
BODY = (FONT_FAMILY, 16)
STRIKE = (FONT_FAMILY, 16, STRIKETHROUGH)
ITALIC = (FONT_FAMILY, 16, ITALIC)
